# Generated by Django 4.2.2 on 2023-07-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=58),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('---', '---'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Finished', 'Finished')], default='Pending', max_length=30),
        ),
    ]
