# Generated by Django 4.2.2 on 2023-08-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_address_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('---', '---'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Finished', 'Finished')], max_length=30),
        ),
    ]
