# Generated by Django 4.2.2 on 2023-08-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
    ]
