# Generated by Django 4.2.2 on 2023-07-23 19:36

from django.db import migrations, models
import web_magazine.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[web_magazine.accounts.models.phone_regex_validator]),
        ),
    ]
