# Generated by Django 4.2.2 on 2023-08-06 12:03

from django.db import migrations, models
import web_magazine.book.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-picture', validators=[web_magazine.book.models.validate_max_size]),
        ),
    ]
