# Generated by Django 4.2.2 on 2023-08-06 11:57

from django.db import migrations, models
import web_magazine.book.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='book_cover', validators=[web_magazine.book.models.validate_max_size]),
        ),
    ]
